filter:
    excluded_paths:
        - 'tests/*'
checks:
    php:
        code_rating: true
        duplication: true
    
php_code_coverage: true
    php_code_sniffer:
        enabled: true
        config:
            standard: PSR2
